name: ${PROJECT_NAME}

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    env_file:
      - .env
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: ${PROJECT_NAME}_node
    depends_on:
      - php
      - nginx
    volumes:
      - ./src:/var/www/html
      - /var/www/html/node_modules
    env_file:
      - .env
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: ${PROJECT_NAME}_redis
    ports:
      - "6379:6379"
    env_file:
      - .env
