<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert(
            [
                [
                    'name' => 'LED Ceiling Light',
                    'title' => 'LED Ceiling Light — потолочный светильник',
                    'slug' => 'luna',
                    'thumbnail' => 'assets/img/products/luna_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'LED Ceiling Light Kids',
                    'title' => 'LED Ceiling Light (для детской)',
                    'slug' => 'kids',
                    'thumbnail' => 'assets/img/products/kids_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'LED Ceiling Light Galaxy',
                    'title' => 'LED Ceiling Light Galaxy — светильник со звездами',
                    'slug' => 'galaxy',
                    'thumbnail' => 'assets/img/products/luna_650_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Crystal Ceiling Light Pro',
                    'title' => 'Crystal Ceiling Light Pro',
                    'slug' => 'nox-pro',
                    'thumbnail' => 'assets/img/products/nox_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Crystal Ceiling Light Plus',
                    'title' => 'Crystal Ceiling Light Plus',
                    'slug' => 'nox-plus',
                    'thumbnail' => 'assets/img/products/nox-plus_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Crystal Ceiling Light Mini',
                    'title' => 'Crystal Ceiling Light Mini — светильник с датчиком движения',
                    'slug' => 'nox-mini',
                    'thumbnail' => 'assets/img/products/nox-mini_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Crystal Ceiling Light Round',
                    'title' => 'Crystal Ceiling Light Round Diamond',
                    'slug' => 'nox-round',
                    'thumbnail' => 'assets/img/products/nox-round_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Yilai Lotus Ceiling Light',
                    'title' => 'Yilai Lotus Ceiling Light',
                    'slug' => 'yilai-lotus',
                    'thumbnail' => 'assets/img/products/lotus-round_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Yilai Snow Ceiling Light',
                    'title' => 'Yilai Snow Ceiling Light',
                    'slug' => 'yilai-snow',
                    'thumbnail' => 'assets/img/products/snow_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Yeelight Pendant',
                    'title' => 'Pendant Light — Подвесной светильник',
                    'slug' => 'pendant',
                    'thumbnail' => 'assets/img/products/pendant_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Ceiling Light Embedded',
                    'title' => 'Embedded Ceiling Light — Встраиваемый светильник',
                    'slug' => 'embedded',
                    'thumbnail' => 'assets/img/products/embedded_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 1,
                ],
                [
                    'name' => 'Ambient Candela',
                    'title' => 'Ambient Lamp Candela — Интерьерная свеча',
                    'slug' => 'candela',
                    'thumbnail' => 'assets/img/products/candella_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 2,
                ],
                [
                    'name' => 'Mi Beside Lamp',
                    'title' => 'Mi Beside Lamp — Прикроватный светильник',
                    'slug' => 'beside',
                    'thumbnail' => 'assets/img/products/beside_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 2,
                ],
                [
                    'name' => 'Motion Sensor Night Lights',
                    'title' => 'Mi Motion Sensor Night Light — Прикроватный светильник',
                    'slug' => 'motion-sensor-nightlight',
                    'thumbnail' => 'assets/img/products/msnl2_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 2,
                ],
                [
                    'name' => 'Motion Sensor Closet Light',
                    'title' => 'Motion Sensor Closet Light — светильник для шкафа',
                    'slug' => 'motion-sensor-closet',
                    'thumbnail' => 'assets/img/products/closet_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 2,
                ],
                [
                    'name' => 'Wireless Charge Nightlight',
                    'title' => 'Wireless Charge Nightlight — ночник-зарядка',
                    'slug' => 'wireless-charge-nightlight',
                    'thumbnail' => 'assets/img/products/wireless-charge_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 2,
                ],
                [
                    'name' => 'LED Smart Desk',
                    'title' => 'LED Smart Table Lamp — Умная настольная лампа',
                    'slug' => 'desk',
                    'thumbnail' => 'assets/img/products/desktop_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'LED Table Lamp',
                    'title' => 'Mi LED Desk Lamp — Настольная лампа',
                    'slug' => 'table-led-light',
                    'thumbnail' => 'assets/img/products/table_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Serene Eye-Friendly',
                    'title' => 'Serene Eye-Friendly — Настольная лампа',
                    'slug' => 'muse',
                    'thumbnail' => 'assets/img/products/muse_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Wireless Charge Nightlight',
                    'title' => 'Wireless Charge Nightlight — ночник-зарядка',
                    'slug' => 'wireless-charge-nightlight',
                    'thumbnail' => 'assets/img/products/wireless-charge_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Sensor Makeup Mirror',
                    'title' => 'Sensor Makeup Mirror — зеркало с подсветкой',
                    'slug' => 'mirror',
                    'thumbnail' => 'assets/img/products/mirror_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Folding Desk Lamp',
                    'title' => 'Folding Desk Lamp — складная настольная лампа',
                    'slug' => 'folding',
                    'thumbnail' => 'assets/img/products/folding_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Folding Lamp Z1 Pro',
                    'title' => 'Folding Z1 Pro — настольная лампа',
                    'slug' => 'folding-z1-pro',
                    'thumbnail' => 'assets/img/products/z1_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Desk Clamp Lamp J1',
                    'title' => 'Desk Clamp Lamp J1 — лампа с зажимом',
                    'slug' => 'clamp',
                    'thumbnail' => 'assets/img/products/clamp_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 3,
                ],
                [
                    'name' => 'Smart Curtain Motor',
                    'title' => 'Yeelight Smart Curtain — умный карниз',
                    'slug' => 'curtain-motor',
                    'thumbnail' => 'assets/img/products/curtain_thumbnail.jpg',
                    'description' => '',
                    'keywords' => '',
                    'category_id' => 4,
                ],
            ]
        );
    }
}
